name: Move LeetCode Solutions

on:
  workflow_dispatch:  # 수동 실행 옵션 유지
  push:
    paths:
      - '[0-9][0-9][0-9][0-9]-*/**'  # LeetHub가 생성하는 폴더 패턴 (예: 0020-valid-parentheses)

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move LeetCode solutions
        run: |
          # LeetCode 폴더가 없다면 생성
          mkdir -p LeetCode
          
          # LeetHub가 생성한 폴더들을 LeetCode 폴더로 이동
          for d in [0-9][0-9][0-9][0-9]-*; do
            if [ -d "$d" ]; then
              mv "$d" "LeetCode/"
            fi
          done

      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "chore: Move LeetCode solutions to LeetCode folder" || echo "No changes to commit"
          git push 