name: GitHub-Profile-3D-Contrib and Contribution SVG

on:
  schedule: # 매일 자정에 실행
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 3D Contribution Graph 생성
      - name: Generate 3D Contribution Graph for this repository
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # 3. Python 스크립트를 사용해 기여도 시각화(SVG 파일 생성)
      - name: Commit history for [1D1A] repository since '2024-11-04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 generate_contribution.py

      # 4. 변경 사항 커밋 및 푸시
      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Updated 3D graph and contribution SVG" || echo "No changes to commit"
          git push
