name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 자정에 실행
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph for this repository
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          REPO: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name eunsoA
          git config user.email eunsoa0310@gmail.com
          git add -A .
          git commit -m "Generated 3D contribution graph"
          git push
