name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v2
        env:
          GITHUB_USER_NAME: eunsoA
        with:
          github_user_name: ${{ env.GITHUB_USER_NAME }}
          outputs: dist/snake.svg

      - name: Check if snake.svg exists
        run: |
          if [ -f dist/snake.svg ]; then echo "snake.svg created"; else echo "snake.svg not found"; exit 1; fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
